apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels: 
    app: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.port }}
      protocol: TCP
      name: http
  selector:
    app: jenkins

